import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'react-quill/dist/quill.snow.css';
import { MSWComponent } from './_components/MSWComponent';
import RQProvider from './_components/RQProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MSWComponent />
        <RQProvider>
          <div className="w-full max-w-xl h-full min-h-screen flex justify-center mx-auto px-4 pt-32">
            {children}
          </div>
        </RQProvider>
      </body>
    </html>
  );
}
